name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "CI is working"

      - name: Build Docker Image
        run: docker build -t docker-fastapi .
